# NumPy
(Numerical Python)

In [1]:
import numpy 

ModuleNotFoundError: No module named 'numpy'

In [2]:
pip install numpy # pip : Package Installer of Pyrhon

# “numpy라는 라이브러리를 인터넷에서 다운받아서 내 파이썬 환경에 설치해줘!” 라는 뜻

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.8 kB 640.0 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 803.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.9 MB 51.6 MB/s eta 0:00:01
   ---------------- ----------------------- 5.2/12.9 MB 55.7 MB/s eta 0:00:01
   ------------------------ --------------- 8.0/12.9 MB 56.7 MB/s eta 0:00:01
   --------------------------------- ------ 10.8/12.9 MB 59.5 MB/s eta 0:00:01
   ---------------------------------------  12.9/12.9 MB 54.7 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 46.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np # numpy 라는 모듈을 vs코드에 불러오고 np라고 줄여부르도록하자. 라는 뜻

In [6]:
np.__version__ # 버전확인하기

'2.2.4'

In [7]:
alist = [1,2,3,4,5,6,7]

In [12]:
print(alist)
print(type(alist))
# 모든 데이터 타입을 클래스로 관리를 한다

[1, 2, 3, 4, 5, 6, 7]
<class 'list'>


In [14]:
ar1 = np.array(alist)
print(ar1)
print(type(ar1))
#numpy.ndarray이라는 타입을 변경을 한 것.

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [17]:
ar1.dtype
#타입 확인가능(정수)

dtype('int64')

In [15]:
ar2 = np.array([1.1, 2.2, 3.3])

In [16]:
ar2

array([1.1, 2.2, 3.3])

In [18]:
ar2.dtype
#타입 확인가능(실수)

dtype('float64')

In [24]:
list_data = [2, 2., 3]

ar3 = np.array(list_data)

print(ar3)
print(ar3.dtype)
print(ar3.ndim)
print(ar3.shape)

[2. 2. 3.]
float64
1
(3,)


In [30]:
arr1 = np.array([1,2,3,4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [31]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [48]:
arr3 = arr2.reshape(-1,3) #-1은 하나 줄인다는건가,,?(맞는듯?)
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [56]:
arr4 = arr2.reshape(2, 2,2) #사이즈가 안맞아서 에러가 남
print(arr4)
print(arr4.ndim)
print(arr4.shape)

ValueError: cannot reshape array of size 12 into shape (2,2,2)

In [ ]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9,10])

In [68]:
from time import process_time

x= np.arange(1, 10000001)
y= np.arange(10000001, 20000001)

z= np.zeros_like(x) # z를 0으로 채워진 변수로 만드는데 x와 같은 크기의 0으로 채워진 변수로 만든 것

start = process_time()

for i in range(10000000):
    z[i] = x[i] + y[i]

end = process_time()

print('time= ',(end-start),z)

time=  1.984375 [10000002 10000004 10000006 ... 29999996 29999998 30000000]


In [69]:
from time import process_time

x= np.arange(1, 10000001)
y= np.arange(10000001, 20000001)

z= np.zeros_like(x) # z를 0으로 채워진 변수로 만드는데 x와 같은 크기의 0으로 채워진 변수로 만든 것

start = process_time()

z= x + y

end = process_time()

print('time= ',(end-start),z)

time=  0.015625 [10000002 10000004 10000006 ... 29999996 29999998 30000000]


In [59]:
print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [60]:
print(alist + 1)
print(alist - 1)
print(alist * 3)
print(alist / 2)

[2 3 4 5 6]
[0 1 2 3 4]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [61]:
from time import process_time

tot = 0
start = process_time()

for i in range(10000001): tot +=1

end = process_time()

print('time= ',(end-start),tot)

time=  0.5 10000001


In [62]:
from time import process_time

tot = 0
start = process_time()

tot = sum(range(10000001))

end = process_time()

print('time= ',(end-start),tot)

time=  0.21875 50000005000000


In [77]:
data = [0,1,2,3,4,5,6,7,8,9]

answer= []

for i in data:
    answer.append(i * 2)

print(answer)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [78]:
data_array= np.array(data)
print(2*data_array)

[ 0  2  4  6  8 10 12 14 16 18]


In [83]:
a= np.array([1,2,3])
b= np.array([10,20,30])

print(2 * a + b)
print(a==b)
print(b>10)
print((a==2) & (b>10))

[12 24 36]
[False False False]
[False  True  True]
[False  True False]


In [95]:
c= np.array([[0,1,2],[3,4,5]])
len(c[1])

3

In [97]:
b= np.array([[0,1,2],[3,4,5]])

In [98]:
print(type(b))

<class 'numpy.ndarray'>


In [104]:
print(b[0,0],b[0,1],b[1,2])

0 1 5


In [113]:
#numpy 배열 슬라이싱

a= np.array([[0,1,2,3],[4,5,6,7]])
print(a)
print(a[0,0:3])
print(a[0,1],a[1,1])
print(a[:,3])

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2]
1 5
[3 7]


In [118]:
print(a[1,1:4])
print(a[:,:2])

[5 6 7]
[[0 1]
 [4 5]]


In [119]:
#팬시인덱싱: 

a= np.array([0,1,2,3,4,5,6,7,8,9])
b= np.array([True, False,True, False,True, False,True, False,True, False])

In [124]:
a[[True, False,True, False,True, False,True, False,True, False]]

array([0, 2, 4, 6, 8])

In [126]:
a%2==0
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [127]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [131]:
# 정수배열 인덱싱
a = np.array([11, 22, 33, 44, 55, 66 ,77, 88, 99])
idx = np.array([0, 6, 4 ,2, 8])
a[idx]

array([11, 77, 55, 33, 99])

In [146]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

idx = np.array([0,3])

print(a)
print('')
print(a[:,[0,3]])
print('')
print(a[[2,0,1],:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  4]
 [ 5  8]
 [ 9 12]]

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [163]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
              12, 13, 14, 15, 16, 17, 18, 19, 20])

print(x[x % 3 == 0]) # 배열에서 3의 배수를 찾으시오

print(x[x % 4 ==1]) # 4로 나누면 1이 남는 수를 찾아주세요.

print(x[(x % 3 == 0) & (x % 4 == 1)]) # 3의 배수면서 4로 나누면 1이 남는 수를 찾아주세요. 
print(x[(x % 3 == 0) and (x % 4 == 1)]) # and는 안됨: ~~잘모르겠음

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [164]:
x = np.array([1, 2, 3.0])
x[0] + x[2]

np.float64(4.0)

In [177]:
a = np.arange(12)
print(a)
b = a.reshape(3,-1)
print(b)
c = a. reshape(2, 2, -1) # 왜 -1 인지를 모르겠음ㅠㅠ(챗지피티는 자동계산해주는 거래)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [178]:
c.flatten() # 납작하게 만들기

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# x.sum() : 더하기?
# x.min() : 최솟값
# x.argmin() : 최솟값의 위치
# x.mean() : 평균값

In [179]:
# pandas

pip install pandas 

   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ------ --------------------------------- 1.8/11.6 MB 37.3 MB/s eta 0:00:01
   --------------- ------------------------ 4.5/11.6 MB 48.1 MB/s eta 0:00:01
   ------------------------ --------------- 7.2/11.6 MB 51.3 MB/s eta 0:00:01
   ---------------------------------- ----- 10.0/11.6 MB 52.9 MB/s eta 0:00:01
   ---------------------------------------  11.6/11.6 MB 59.5 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 50.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/509.2 kB ? eta -:--:--
   --------------------------------------- 509.2/509.2 kB 31.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/347.8 kB ? eta -:--:--
   ---------------------------------------- 347.8/347.8 kB ? eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [182]:
import pandas as pd

In [183]:
pd.__version__

'2.2.3'

In [319]:
#read_csv(): .csv파일을 읽는 pandas 함수

df = pd.read_csv('heroes.csv') 
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [189]:
# .head() : 앞에서 3개

df.head(3)

이름  나이    직업     국적    키            재산
0   아이언맨  58   CEO     미국  174  1.150000e+10
1     토르  45     신  아스가르드  190           NaN
2  스파이더맨  18  고등학생     미국  177  6.000000e+02

In [188]:
# .tail() : 뒤에서 3개

df.tail(3)

이름  나이     직업   국적    키            재산
4     헐크  33  핵물리학자   미국  270  1.000000e+09
5   캡틴마블  25    파일럿   미국  170  3.400000e+08
6  블랙위도우  32    스파이  러시아  170  5.000000e+07

In [192]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [193]:
df.describe()

나이           키            재산
count   7.000000    7.000000  5.000000e+00
mean   34.000000  189.857143  2.578000e+09
std    13.466007   35.983462  5.003441e+09
min    18.000000  170.000000  6.000000e+02
25%    26.000000  172.000000  5.000000e+07
50%    32.000000  177.000000  3.400000e+08
75%    39.000000  184.000000  1.000000e+09
max    58.000000  270.000000  1.150000e+10

In [194]:
pd.options.display.float_format = '{:.0f}'.format

In [195]:
df.head()

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000

In [197]:
df.tail(3)

이름  나이     직업   국적    키         재산
4     헐크  33  핵물리학자   미국  270 1000000000
5   캡틴마블  25    파일럿   미국  170  340000000
6  블랙위도우  32    스파이  러시아  170   50000000

In [198]:
df.describe()

나이   키          재산
count   7   7           5
mean   34 190  2578000120
std    13  36  5003440739
min    18 170         600
25%    26 172    50000000
50%    32 177   340000000
75%    39 184  1000000000
max    58 270 11500000000

In [203]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [204]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [ ]:
df['나이'].nlargest() # .nlargest(갯수) : 큰것부터

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [210]:
df.nlargest(7, '재산')

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000
2  스파이더맨  18   고등학생     미국  177         600
1     토르  45      신  아스가르드  190         NaN
3   원더우먼  27     공주  데미스키라  178         NaN

In [ ]:
type(df['이름']) # 타입: 시리즈

pandas.core.series.Series

In [218]:
df[['이름','직업','키']]

이름     직업    키
0   아이언맨    CEO  174
1     토르      신  190
2  스파이더맨   고등학생  177
3   원더우먼     공주  178
4     헐크  핵물리학자  270
5   캡틴마블    파일럿  170
6  블랙위도우    스파이  170

In [219]:
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [221]:
# .iloc[행번호,열번호]

df.iloc[0,0]

'아이언맨'

In [222]:
df.iloc[[1,3,6]]

이름  나이   직업     국적    키       재산
1     토르  45    신  아스가르드  190      NaN
3   원더우먼  27   공주  데미스키라  178      NaN
6  블랙위도우  32  스파이    러시아  170 50000000

In [226]:
df.iloc[2:7,:4]

이름  나이     직업     국적
2  스파이더맨  18   고등학생     미국
3   원더우먼  27     공주  데미스키라
4     헐크  33  핵물리학자     미국
5   캡틴마블  25    파일럿     미국
6  블랙위도우  32    스파이    러시아

In [229]:
df2 = df.copy()
df2

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [235]:
df2.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
df2

이름  나이     직업     국적    키          재산
a   아이언맨  58    CEO     미국  174 11500000000
b     토르  45      신  아스가르드  190         NaN
c  스파이더맨  18   고등학생     미국  177         600
d   원더우먼  27     공주  데미스키라  178         NaN
e     헐크  33  핵물리학자     미국  270  1000000000
f   캡틴마블  25    파일럿     미국  170   340000000
g  블랙위도우  32    스파이    러시아  170    50000000

In [237]:
df2.loc['c','직업']

'고등학생'

In [238]:
df2.loc['d':'g','이름':'국적']

이름  나이     직업     국적
d   원더우먼  27     공주  데미스키라
e     헐크  33  핵물리학자     미국
f   캡틴마블  25    파일럿     미국
g  블랙위도우  32    스파이    러시아

In [ ]:
# 나이가 30초과, 50미만인 레코드만 추출

In [246]:
df[ (df['나이']>30) & (df['나이']<50) ]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [252]:
# 키 180이상인 이름과, 나이컬럼만 출력

df.loc[df['키'] > 180, ['이름','직업']]

이름     직업
1  토르      신
4  헐크  핵물리학자

In [254]:
df['국적'] = '대한민국'
df

이름  나이     직업    국적    키          재산
0   아이언맨  58    CEO  대한민국  174 11500000000
1     토르  45      신  대한민국  190         NaN
2  스파이더맨  18   고등학생  대한민국  177         600
3   원더우먼  27     공주  대한민국  178         NaN
4     헐크  33  핵물리학자  대한민국  270  1000000000
5   캡틴마블  25    파일럿  대한민국  170   340000000
6  블랙위도우  32    스파이  대한민국  170    50000000

In [256]:
df['전투력'] = [98, 89, 77, 70, 93, 85 ,75]
df

이름  나이     직업    국적    키          재산  전투력
0   아이언맨  58    CEO  대한민국  174 11500000000   98
1     토르  45      신  대한민국  190         NaN   89
2  스파이더맨  18   고등학생  대한민국  177         600   77
3   원더우먼  27     공주  대한민국  178         NaN   70
4     헐크  33  핵물리학자  대한민국  270  1000000000   93
5   캡틴마블  25    파일럿  대한민국  170   340000000   85
6  블랙위도우  32    스파이  대한민국  170    50000000   75

In [259]:
df['전투력'] -=5
df

이름  나이     직업    국적    키          재산  전투력
0   아이언맨  58    CEO  대한민국  174 11500000000   93
1     토르  45      신  대한민국  190         NaN   84
2  스파이더맨  18   고등학생  대한민국  177         600   72
3   원더우먼  27     공주  대한민국  178         NaN   65
4     헐크  33  핵물리학자  대한민국  270  1000000000   88
5   캡틴마블  25    파일럿  대한민국  170   340000000   80
6  블랙위도우  32    스파이  대한민국  170    50000000   70

In [265]:
df.columns = ['성명', '연령', '하는 일','사는 곳', '신장', '돈', '파워',]
df

성명  연령   하는 일  사는 곳   신장           돈  파워
0   아이언맨  58    CEO  대한민국  174 11500000000  93
1     토르  45      신  대한민국  190         NaN  84
2  스파이더맨  18   고등학생  대한민국  177         600  72
3   원더우먼  27     공주  대한민국  178         NaN  65
4     헐크  33  핵물리학자  대한민국  270  1000000000  88
5   캡틴마블  25    파일럿  대한민국  170   340000000  80
6  블랙위도우  32    스파이  대한민국  170    50000000  70

In [ ]:
df = df.drop(columns=['사는 곳']) 
# = df.drop(columns=['사는 곳'], inplace=True)  
# #inplace=True: 변경값 적용

In [269]:
df

성명  연령   하는 일   신장           돈  파워
0   아이언맨  58    CEO  174 11500000000  93
1     토르  45      신  190         NaN  84
2  스파이더맨  18   고등학생  177         600  72
3   원더우먼  27     공주  178         NaN  65
4     헐크  33  핵물리학자  270  1000000000  88
5   캡틴마블  25    파일럿  170   340000000  80
6  블랙위도우  32    스파이  170    50000000  70

In [272]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [274]:
df[df['재산'].isnull()]

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [275]:
df.isnull().sum()

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [282]:
df.dropna()
# .dropna(): null 값있는 행 삭제
df


이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [290]:
df['재산'].fillna(df['재산'].mean(), inplace=True)
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190  2578000120
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178  2578000120
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [ ]:
df.fillna(method='bfill')
# fillna() : 

C:\Users\wlsehq\AppData\Local\Temp\ipykernel_19540\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')


이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         600
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178  1000000000
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [293]:
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [ ]:
df.iloc[5, 1] = np.nan
#np.nan : 넘파이에서 쓰는 '값이 없음'
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블 NaN    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [322]:
df['나이'].fillna(df['나이'].mean(), inplace=True)

C:\Users\wlsehq\AppData\Local\Temp\ipykernel_19540\3751468051.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['나이'].fillna(df['나이'].mean(), inplace=True)


In [324]:
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  36    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [ ]:
df['키'].apply(lambda x: f'{x}cm') #미칭,,

0    174cm
1    190cm
2    177cm
3    178cm
4    270cm
5    170cm
6    170cm
Name: 키, dtype: object